/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ramonjtorres
 */
public class CivitasView extends javax.swing.JFrame {
    
    CivitasJuego juego;
    JugadorPanel jugadorPanel;
    CasillaPanel casillaPanel;
    GestionarDialog gestionarD;

    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        
        jugadorPanel = new JugadorPanel();
        contenedorVistaJugador.add(jugadorPanel);
        
        casillaPanel = new CasillaPanel();
        contenedorVistaCasilla.add(casillaPanel);
        
        gestionarD = new GestionarDialog(this);
        
        repaint();
        revalidate();
    }
    
    public void setCivitasJuego(CivitasJuego civitas){ 
        juego = civitas;
        this.actualizarVista();
        this.setVisible(true);

    }
    
    void actualizarVista(){
  
      ranking.setVisible(false);
      TextoRanking.setVisible(false);
      panelRanking.setVisible(false);
        
      jugadorPanel.setJugador(juego.getJugadorActual());
      casillaPanel.setCasilla(juego.getCasillaActual());
      
      if(juego.finalDelJuego()){
          
          ArrayList<String> nombresRanking = new ArrayList<String>();
          int i = 1;
          
          for(Jugador j : juego.ranking()){
              
                nombresRanking.add(i + "º " + j.getNombre() + "\n");
                i++;
          }
          
          TextoRanking.setText(nombresRanking.toString());
          
          ranking.setVisible(true);
          TextoRanking.setVisible(true);
          panelRanking.setVisible(true);
          
          repaint();
          revalidate();
      }
      
    } 

    void mostrarSiguienteOperacion(Operaciones_juego operacion){
  
      TextoOperacion.setText(operacion.name());
        
      this.actualizarVista();
      
    } 
    
    void mostrarEventos(){
        
        DiarioDialog diarioD = new DiarioDialog(this); //crea la ventana del diario
    }
    
    Respuestas comprar(){
    
        int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?",
        "Compra", JOptionPane.YES_NO_OPTION);
        
        return Respuestas.values()[opcion];
    }
    
    public int getGestion(){
    
        return gestionarD.getGestion();
    }
    
    public int getPropiedad(){
    
        return gestionarD.getPropiedad();
    }
    
    public void gestionar(){
    
        gestionarD.gestionar(juego.getJugadorActual());
        
        gestionarD.pack();
        gestionarD.repaint();
        gestionarD.revalidate();
        
        gestionarD.setVisible(true);
    }
    
    SalidasCarcel salirCarcel(){
    
        String[] opciones = {"Pagando", "Tirando"};
        
        int respuesta = JOptionPane.showOptionDialog(null, "¿Cómo quieres salir de la cárcel?", 
                "Salir de la cárcel", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, opciones, opciones[0]);
        
        return SalidasCarcel.values()[respuesta];
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CivitasJuego = new javax.swing.JLabel();
        contenedorVistaJugador = new javax.swing.JPanel();
        contenedorVistaCasilla = new javax.swing.JPanel();
        SiguienteOperacion = new javax.swing.JLabel();
        TextoOperacion = new javax.swing.JTextField();
        ranking = new javax.swing.JPanel();
        panelRanking = new javax.swing.JScrollPane();
        TextoRanking = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CivitasJuego.setText("Civitas El Juego");

        contenedorVistaJugador.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador Actual"));

        contenedorVistaCasilla.setBorder(javax.swing.BorderFactory.createTitledBorder("Casilla Actual"));

        SiguienteOperacion.setText("Siguiente Operación: ");

        TextoOperacion.setBackground(new java.awt.Color(250, 250, 250));
        TextoOperacion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextoOperacion.setEnabled(false);

        ranking.setBorder(javax.swing.BorderFactory.createTitledBorder("Ranking"));
        ranking.setEnabled(false);

        TextoRanking.setBackground(new java.awt.Color(250, 250, 250));
        TextoRanking.setColumns(20);
        TextoRanking.setRows(5);
        TextoRanking.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextoRanking.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextoRanking.setEnabled(false);
        panelRanking.setViewportView(TextoRanking);

        ranking.add(panelRanking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CivitasJuego)
                .addGap(0, 809, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SiguienteOperacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedorVistaCasilla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ranking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CivitasJuego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SiguienteOperacion)
                            .addComponent(TextoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contenedorVistaCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 382, Short.MAX_VALUE))
        );

        CivitasJuego.getAccessibleContext().setAccessibleName("Titulo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CivitasJuego;
    private javax.swing.JLabel SiguienteOperacion;
    private javax.swing.JTextField TextoOperacion;
    private javax.swing.JTextArea TextoRanking;
    private javax.swing.JPanel contenedorVistaCasilla;
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JScrollPane panelRanking;
    private javax.swing.JPanel ranking;
    // End of variables declaration//GEN-END:variables
}
