/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.*;
import java.util.ArrayList;

/**
 *
 * @author ramonjtorres
 */
public class JugadorPanel extends javax.swing.JPanel {

    Jugador jugador;
    
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }
    
    void setJugador(Jugador j){
    
        String t, e;
        
        this.jugador = j;
     
        if(this.jugador.isEncarcelado())
            t = "Sí";
        else
            t = "No";

        if("Especulador".equals(this.jugador.getClass().toString()))
            e = "Sí";
        else
            e = "No";
               
        TextoNombre.setText(this.jugador.getNombre());
        TextoSaldo.setText(Float.toString(this.jugador.getSaldo()));
        TextoEncarcelado.setText(t);
        TextoEspeculador.setText(e);
        
        this.rellenaPropiedades(this.jugador.getPropiedades());
        
        this.repaint();
        this.revalidate();
    }
    
    private void rellenaPropiedades(ArrayList<TituloPropiedad> lista){
    
        // Se elimina la información antigua
        propiedades.removeAll();
        
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y
        //añadirlas al panel
        for (TituloPropiedad t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            propiedades.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        
        // Se fuerza la actualización visual del panel propiedades y del panel del jugador
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        Saldo = new javax.swing.JLabel();
        TextoSaldo = new javax.swing.JTextField();
        Encarcelado = new javax.swing.JLabel();
        TextoEncarcelado = new javax.swing.JTextField();
        Especulador = new javax.swing.JLabel();
        TextoEspeculador = new javax.swing.JTextField();
        propiedades = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Nombre.setText("Nombre:");

        TextoNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextoNombre.setEnabled(false);
        TextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreActionPerformed(evt);
            }
        });

        Saldo.setText("Saldo:");

        TextoSaldo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextoSaldo.setEnabled(false);

        Encarcelado.setText("Encarcelado:");

        TextoEncarcelado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextoEncarcelado.setEnabled(false);

        Especulador.setText("Especulador:");

        TextoEspeculador.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextoEspeculador.setEnabled(false);

        propiedades.setBorder(javax.swing.BorderFactory.createTitledBorder("Propiedades"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(propiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextoNombre))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Encarcelado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextoEncarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Especulador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextoEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Especulador)
                        .addComponent(TextoEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Encarcelado)
                            .addComponent(TextoEncarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Saldo)
                            .addComponent(TextoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)))
                .addGap(18, 18, 18)
                .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encarcelado;
    private javax.swing.JLabel Especulador;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Saldo;
    private javax.swing.JTextField TextoEncarcelado;
    private javax.swing.JTextField TextoEspeculador;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoSaldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel propiedades;
    // End of variables declaration//GEN-END:variables
}
